# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci_two_terms = [1,1]
limit = 4000000
sum = 0
next_value = 0
begin_time = Time.now

while next_value < limit do
	if next_value % 2 == 0
		sum += next_value
	end
	next_value = fibonacci_two_terms[0] + fibonacci_two_terms[1]
	fibonacci_two_terms[0] = fibonacci_two_terms[1]
	fibonacci_two_terms[1] = next_value
end

end_time = Time.now
puts "Solution: #{sum}. Found in #{end_time - begin_time} ms"

